### ISSUE TITLE
Check fails with channel not found, when channel specified 

### ISSUE THREAD

**Issue by natalytvinova** [canonical/ua-reviewkit#35]
Vault channel is specified in the bundle, but the check fails
[ua-bundle-checks.openstack (1).log](https://github.com/canonical/ua-reviewkit/files/12462728/ua-bundle-checks.openstack.1.log)

vault:
    bindings:
      ? ''
      : oam-space
      certificates: internal-space
      etcd: internal-space
      secrets: internal-space
      shared-db: internal-space
    channel: 1.8/stable
    charm: vault
    num_units: 3
    series: jammy
    to:
    - '10'
    - '11'
    - '9'
    
Will send the full bundle privately

**Comment by dosaboy** [comment]
Ok so I checked this out using the provided bundle and the issue is in fact not a bug per se because the "channel" config option is indeed unset. Note the check is for the config option and not the charm channel. This was written to fail if unset because older versions of the charm has non-sensible defaults (specifically "stable" which now gives an unsupported version of vault). New versions of the vault charm have sensible defaults like 1.8/stable for the 1.8 charm. So this option can at least be made to WARN rather than ERROR.
